export const teamHeads = [
  {
    name: 'Alice Johnson',
    position: 'Software Engineer',
    title: 'Team Lead',
    imageSrc: '/images/alice.jpg',
  },
  {
    name: 'Bob Smith',
    position: 'Product Designer',
    title: 'UX Head',
    imageSrc: '/images/bob.jpg',
  },
  {
    name: 'Charlie Brown',
    position: 'Data Analyst',
    title: 'Analytics Lead',
    imageSrc: '/images/charlie.jpg',
  },
  {
    name: 'Diana Prince',
    position: 'Marketing Manager',
    title: 'Marketing Head',
    imageSrc: '/images/diana.jpg',
  },
  {
    name: 'Ethan Hunt',
    position: 'Cybersecurity Expert',
    title: 'Security Lead',
    imageSrc: '/images/ethan.jpg',
  },
];

export const members = [
  { name: 'Anmol Pattnayak', image: '/images/member-1.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-2.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-3.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-4.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-5.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-6.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-7.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-8.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-9.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-10.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-11.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-12.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-13.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-14.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-15.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-16.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-17.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-18.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-19.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-20.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-21.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-22.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-23.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-24.jpg' },
  { name: 'Anmol Pattnayak', image: '/images/member-25.jpg' },
];
